### ISSUE TITLE
Bug: Flipped tooltips

### ISSUE THREAD

**Issue by pablobove** [gskinner/regexr#398]
If the tooltip add the class flipped it not show correctly.
The problem is in the value in the transform in y axis, increasing it to -115% fix the bug.   

```scss
&.flipped {
	transform: translate(-50%, -100%);
	.tip {
		transform: scale(1, 1);
		order: 1;
	}
}
```
